### ISSUE TITLE
Fan speed always one step lower than chosen

### ISSUE THREAD

**Issue by Morjgus** [laszlojakab/homeassistant-easycontrols#1]
When setting the fan speed through Homeassistant, the applied value is always lowered by one. rated->basic, intensive->rated, maximum->intensive. Maximum cannot be set. Setting basic turn the fan off.

**Comment by laszlojakab** [comment]
@Morjgus have you set minimum fan speed to 0?

![image](https://user-images.githubusercontent.com/6196882/103174804-592dc280-4865-11eb-9ea1-2c817af55f30.png)

**Comment by Morjgus** [comment]
Yes, minimum fan speed is 0.

![2020-12-27 18 07 23 helios fritz box 8f0e0ca6-d5d2-4f68-9c6c-8c3db221fa7e](https://user-images.githubusercontent.com/24867679/103176004-b4b07e00-486e-11eb-9226-6fd6da266eac.jpg)

**Comment by laszlojakab** [comment]
OK, as I see the problem still exists in v0.1.0
