### ISSUE TITLE
easyControls 3.0

### ISSUE THREAD

**Issue by sanchosk** [laszlojakab/homeassistant-easycontrols#102]
Is there any chance of getting support for easyControls 3.0?
I checked the communication using web browser, it seems to open webSocket connection and the communicates and delivers data using the webSocket. From what I can see, it seems to me like the websocket actually sends and receives binary data, perhaps ModBus data?

**Comment by laszlojakab** [comment]
Sorry, not from me. I don't have a device with easyControls 3.0, and unfortunately, I also don't have the time for such a big task. If someone creates a python package which can be used to query these devices by variable names then _maybe_ I could add to this integration.

**Comment by mgrfilipmarek** [comment]
EasyControls 3.0 is supported by this integration: https://github.com/frawe/EasyControls3_homeassistant
