### ISSUE TITLE
deprecated supported features

### ISSUE THREAD

**Issue by djm193** [laszlojakab/homeassistant-easycontrols#106]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1567
First occurred: 14. Februar 2024 um 12:11:59 (1 occurrences)
Last logged: 14. Februar 2024 um 12:11:59
Entity None (<class 'custom_components.easycontrols.fan.EasyControlsFanDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <FanEntityFeature.SET_SPEED|PRESET_MODE: 9>, please create a bug report at https://github.com/laszlojakab/homeassistant-easycontrols/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by laszlojakab** [comment]
Fixed in #111. It will be in the next release.
