### ISSUE TITLE
 SUPPORT_PRESET_MODE deprecated

### ISSUE THREAD

**Issue by djm193** [laszlojakab/homeassistant-easycontrols#107]
Logger: homeassistant.components.fan
Source: helpers/deprecation.py:205
Integration: Lüfter ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 14. Februar 2024 um 12:11:56 (4 occurrences)
Last logged: 14. Februar 2024 um 12:11:56

    SUPPORT_PRESET_MODE was used from easycontrols, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/laszlojakab/homeassistant-easycontrols/issues
    SUPPORT_SET_SPEED was used from easycontrols, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please create a bug report at https://github.com/laszlojakab/homeassistant-easycontrols/issues

**Comment by laszlojakab** [comment]
Fixed in #111. It will be in the next release.
