### ISSUE TITLE
Cannot install integration

### ISSUE THREAD

**Issue by Ing-Dom** [laszlojakab/homeassistant-easycontrols#109]
when I follow the instruction in the Readme.md an click this link
[C:\Users\dosp\Desktop\2024-04-27 11_50_44-Settings – Home Assistant – Mozilla Firefox.png](https://my.home-assistant.io/redirect/config_flow_start/?domain=easycontrols)
I'm first redirected to some page where I can insert my HA url - I do it. It works, after that I get this error message

![2024-04-27 11_50_44-Settings – Home Assistant – Mozilla Firefox](https://github.com/laszlojakab/homeassistant-easycontrols/assets/12643772/d28e6752-c262-43f4-aa4b-37fd335378cf)

**Comment by rbhun** [comment]
you have to press download first

**Comment by laszlojakab** [comment]
@Ing-Dom is this solved?
