### ISSUE TITLE
Set FanEntityFeature.TURN_OFF instead of implementing the turn_off method

### ISSUE THREAD

**Issue by flattermues** [laszlojakab/homeassistant-easycontrols#116]
Logger: homeassistant.components.fan
Quelle: components/fan/__init__.py:295
Integration: Lüfter (Dokumentation, Probleme)
Erstmals aufgetreten: 10. Oktober 2024 um 11:02:16 (2 Vorkommnisse)
Zuletzt protokolliert: 10. Oktober 2024 um 11:02:16

    Entity None (<class 'custom_components.easycontrols.fan.EasyControlsFanDevice'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/laszlojakab/homeassistant-easycontrols/issues
    Entity None (<class 'custom_components.easycontrols.fan.EasyControlsFanDevice'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/laszlojakab/homeassistant-easycontrols/issues

**Comment by laszlojakab** [comment]
Thanks, already solved in https://github.com/laszlojakab/homeassistant-easycontrols/commit/e36ec26b42a9b00634fe6a5fb84f3207aaec4be1. Commit is already in [develop](https://github.com/laszlojakab/homeassistant-easycontrols/tree/develop) but has not been released yet.

This will be released soon.
