### ISSUE TITLE
Deprecated call to async_forward_entry_setup

### ISSUE THREAD

**Issue by flattermues** [laszlojakab/homeassistant-easycontrols#117]
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:188
Erstmals aufgetreten: 17. Oktober 2024 um 17:09:40 (3 Vorkommnisse)
Zuletzt protokolliert: 17. Oktober 2024 um 17:09:40

    Detected that custom integration 'easycontrols' calls async_forward_entry_setup for integration, easycontrols with title: Helios KWL EC 200W L (Helios) and entry_id: d590a7cdc1332df9dd73fab3b8af1ca5, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/easycontrols/__init__.py, line 58: hass.async_create_task(, please create a bug report at https://github.com/laszlojakab/homeassistant-easycontrols/issues

**Comment by laszlojakab** [comment]
Thanks, already solved in https://github.com/laszlojakab/homeassistant-easycontrols/commit/847d26c274fc2e08e649fa342c4d09006fa77016. Commit is already in [develop](https://github.com/laszlojakab/homeassistant-easycontrols/tree/develop) but has not been released yet.

This will be released soon.
