### ISSUE TITLE
Set Fan Speed and switch to Auto Mode

### ISSUE THREAD

**Issue by h4sk33r** [laszlojakab/homeassistant-easycontrols#14]
Hi,

first of all thank you very much for the excellent integration into home assistant.
Unfortunately I'm very new to this and I am therefore not able to change the fan speed or operation mode within Home Assistant (auto/manual). Can you please share a code snippet or explanation on this. 

best regards.

**Comment by laszlojakab** [comment]
@h4sk33r did you solved your problem?

**Comment by h4sk33r** [comment]
Hi, 
thank you very much for responding. I did solve my issues. I did find the registered service to set the fan level. For the "Auto"-Mode I basically wrote an automation, that works a lot better then the Helios one, as it can react to various sensors around my home.
