### ISSUE TITLE
Actions speed fans

### ISSUE THREAD

**Issue by xavax59** [laszlojakab/homeassistant-easycontrols#2]
Hello, 
Is it possible to change speed ?
How do you change the 4 preset speeds?
![image](https://user-images.githubusercontent.com/54884656/104576896-1b98aa00-5659-11eb-877a-6acdbaca7e92.png)
Thank you for this great job!

**Comment by laszlojakab** [comment]
Hi @xavax59,
You can change the speed of fan device in HA: 

![image](https://user-images.githubusercontent.com/6196882/104833297-e0d08500-5897-11eb-85b4-d8c9c96302e5.png)

Is this what you looking for?
These speed values are the same you can set on "initial operation" page of easy controls:

![image](https://user-images.githubusercontent.com/6196882/104833437-f1cdc600-5898-11eb-87ff-b63665e58d41.png)
