### ISSUE TITLE
Fan is off when Frost Protection is active

### ISSUE THREAD

**Issue by asev** [laszlojakab/homeassistant-easycontrols#4]
When Front Protection is active fan entity is marked as off. 
My ventilation is working. At least half of it, because Front protection disables air supply. Only air extraction is working. Still I expect that fan entity would be on.

![image](https://user-images.githubusercontent.com/10020928/104856964-fd170500-591d-11eb-9c45-9d84a51df92f.png)

**Comment by laszlojakab** [comment]
@asev could you please test it in v0.2.2-beta release? I have never seen active frost protection. Maybe because I have a preheater in my ventilation unit.

**Comment by asev** [comment]
I can't test it anymore. It was -20℃ outside and now it's +3℃ :)
Actually I have preheater running as well. But when temperature hit -15℃ it didn't help.

**Comment by asev** [comment]
I can confirm. It works fine now. Fan entity is on.

Just a small notice. Supply fan stage stays at 2 even when supply fan rpm are 0.

![image](https://user-images.githubusercontent.com/10020928/107129529-a4a8a700-68ce-11eb-8144-793bdb1b2ed7.png)

**Comment by laszlojakab** [comment]
Thanks for the confirmation. Fan stage is directly queried from ventilation device. So probably this is a bug in device firmware (or it's by design, I don't know).
