### ISSUE TITLE
Deployment troubles since HA 2022.2

### ISSUE THREAD

**Issue by knorp** [laszlojakab/homeassistant-easycontrols#61]
Hi,
Since this year I'm struggling to update my HA installation because easycontrols doesn't launch anymore and so far I haven't found the cause for it. 

Last (tested) working HA version: 2021.12.9 / easycontrols 0.2.3

The most recent test was with:
HA 2022.3.1 (docker, pulled from tag "ghcr.io/home-assistant/raspberrypi3-homeassistant:stable")
easycontrols release 0.50 (installed as manual deployment in <config>/custom_components)

The integration doesn't load with this error in HA:

```This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/easycontrols/__init__.py:50
Integration: Helios Easy Controls (documentation, issues)
First occurred: 8:45:09 PM (1 occurrences)
Last logged: 8:45:09 PM

Error setting up entry Helios KWL EC 370W R (KWL) for easycontrols
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/easycontrols/__init__.py", line 50, in async_setup_entry
    if not is_controller_exists(hass, config_entry.data[CONF_MAC]):
KeyError: 'mac'
```

**Comment by laszlojakab** [comment]
Hi @knorp,
Please try to remove the installed device from HA and readd it. The mentioned `mac` field in the error message related to a breaking change which was introduced in v0.5.0.

**Comment by knorp** [comment]
Hi,
thanks for the quick response! 

**Removing the whole integration and re-adding it worked like a charm**. With the same name assigned no previous dashboards etc have been impacted by it either.
