### ISSUE TITLE
feat: raise ConfigEntryNotReady for connection error on startup

### ISSUE THREAD

**Issue by laszlojakab** [laszlojakab/homeassistant-easycontrols#75]
### Description

The integration should raise ConfigEntryNotReady in case of connection error during startup: https://developers.home-assistant.io/docs/integration_quality_scale_index?_highlight=configentrynotready#gold-

Related issue: https://github.com/laszlojakab/homeassistant-easycontrols/issues/66#issuecomment-1096564713

**Comment by laszlojakab** [comment]
@MrSimpa Could you please try this version of the integration: https://github.com/laszlojakab/homeassistant-easycontrols/tree/feat/raise-config-entry-not-ready ? Please let me know if it solves your problem.

**Comment by MrSimpa** [comment]
> @MrSimpa Could you please try this version of the integration: https://github.com/laszlojakab/homeassistant-easycontrols/tree/feat/raise-config-entry-not-ready ? Please let me know if it solves your initial TimeoutError problem.

I just updated and for now all good. No ERROR and no Warning after restart. Thank you!

**Comment by laszlojakab** [comment]
Modification released in version 0.5.7
