### ISSUE TITLE
Version key missing

### ISSUE THREAD

**Issue by Wolfy999** [laszlojakab/homeassistant-easycontrols#9]
This custom component fails to load after upgrading to HA 2021.6 version due to lack of version key.
https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions
The version key is required from Home Assistant version 2021.6

**Comment by laszlojakab** [comment]
I haven't installed 2021.6 yet so I can't test it, but version key already included in integration v0.2.3. Do you use v0.2.3 easycontrols integration?

**Comment by Wolfy999** [comment]
Yes, I have v0.2.3. The error message in the logs pointed to this issue and blog article. Also tried to reinstall your integration but did not help. So I reverted to a backup made before upgrade to 2021.6

**Comment by Wolfy999** [comment]
Retried upgrade with latest 2021.6.6 and it works now. I assume it was a HA issue. Thank you!

**Comment by laszlojakab** [comment]
Thanks for reporting!
